name: Generate a new card
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 12 * * *'
jobs:
  generate-card:
    name: Generate a new card
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: json

      # https://github.com/marketplace/actions/checkout
      - name: Checkout pokemon-card-generator-database
        uses: actions/checkout@v3

      - name: Generate card
        run: |
          git clone https://github.com/robiningelbrecht/pokemon-card-generator.git
          cd ./pokemon-card-generator
          composer install --prefer-dist
          
          touch .env

          echo ENVIRONMENT=dev >> .env
          echo DISPLAY_ERROR_DETAILS=1 >> .env
          echo LOG_ERRORS=0 >> .env
          echo LOG_ERROR_DETAILS=0 >> .env
          echo OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }} >> .env
          echo REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }} >> .env

          bin/console app:card:generate
          
          cd ..
          composer install --prefer-dist
          bin/console app:card:copy "pokemon-card-generator"
          
          rm -Rf pokemon-card-generator
      - name: Commit and push changes
        run: |
          git config --global user.name 'robiningelbrecht'
          git config --global user.email 'robiningelbrecht@users.noreply.github.com'
          git add .
          git status
          git diff --staged --quiet || git commit -m"Added new card"
          git push
