name: Generate a new card (png)
on:
  workflow_dispatch:
jobs:
  generate-card:
    name: Generate a new card
    runs-on: ubuntu-latest
    container: robiningelbrecht/pokemon-card-generator:1.0
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout gotta-generate-em-all
        uses: actions/checkout@v3

      - name: Generate card
        run: |
          git clone https://github.com/robiningelbrecht/pokemon-card-generator.git
          cd ./pokemon-card-generator
          composer install --prefer-dist
          
          touch .env

          echo ENVIRONMENT=dev >> .env
          echo DISPLAY_ERROR_DETAILS=1 >> .env
          echo LOG_ERRORS=0 >> .env
          echo LOG_ERROR_DETAILS=0 >> .env
          echo OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }} >> .env
          echo REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }} >> .env

          bin/console app:card:generate -f svg
          
          cd ..
          composer install --prefer-dist
          bin/console app:card:copy "pokemon-card-generator"
          bin/console app:build:site
          
          rm -Rf pokemon-card-generator
